language: julia

os:
  - windows

julia:
  - 1.5

notifications:
  email:
    - omastto1@fel.cvut.cz

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

jobs:
  include:
    - stage: "Test"
      julia: 1.5
      os: linux
      script:
        - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("FiniteHorizonPOMDPs"; coverage=true)'
